import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='z-[1] relative'>{children}</div>
        <div id='modal-level-1' className='z-[2] relative' />
        <div id='modal-level-2' className='z-[3] relative' />
        <div id='modal-level-3' className='z-[4] relative' />
        <div id='modal-level-4' className='z-[5] relative' />
        <div id='modal-level-5' className='z-[6] relative' />
      </body>
    </html>
  )
}
